version: '3.2'

# swag reverse proxy network
networks:
  schmoekerei:
    external: true

services:
  duolingo-data:
    build: .
    container_name: duolingo-data
    restart: unless-stopped
    environment:
      - TIMEZONE=Europe/Berlin
    # ports:
    #   - 80:7000
    networks:
      - schmoekerei
