version: '3.2'

# e.g. swag reverse proxy network
networks:
  yourNetwork:
    external: true

services:
  duolingo-data:
    image: ghcr.io/marvinscham/duolingo-api-dockerized:latest
    container_name: duolingo-data
    restart: unless-stopped
    environment:
      - TIMEZONE=Europe/Berlin
      - DUO_USERNAME=yourUsername
      - DUO_JWT=yourJWT
      - SERVER_URL=https://duo.your-domain.com
      - XP_SUMMARY_DAYS=30
      - UPDATE_INTERVAL=15
      - MAX_RETRIES=3
    # ports:
    #   - 80:7000
    networks:
      - yourNetwork
